server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password: wn1YnaLDE8P1127oASN5CnS75o6ENwqFnKjNNue0PBcfpup7YgF2a5iUIMmg
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  devtools:
    restart:
      #热部署生效
      enabled: true
logging:
  config: log4j2.xml


